/*
See LICENSE file in root folder
*/
#ifndef ___EMUSE_SCRIPT_FUNCTIONS___
#define ___EMUSE_SCRIPT_FUNCTIONS___

/**********************************
	List of prefixes :

	Gen : general code
	Ope : operators
	Ent : entity
	Tmr : timer
	Ve3 : vector3
	Qua : quaternion
	OvE : overlay elements
	OvL : overlays
	ScN : scene nodes
	Cam : camera
	CTx : camtex
	Lgh : light
	Arr : array
	Col : colour
	Snd : sound
	Pll : sound playlist
	Vid : video
	Tim : time
	Spc : special
	Cst : casts
	Mth : math
	Str : string
	Chr : char
	Mir : mirrors
	Sce : scene
	AoG : animated object group
	AOb : animated object
	Ani : animation
	PhS : physics simulation
	PhM : physics material
	POb : physics object
	Uni : universe
	Mat : materials
	Wim : WebImage

**********************************/


#include "Module_Script.h"
#include "Module_Main.h"

#include <tuple>

#include "ScriptNode.h"

namespace Elypse
{
	namespace Script
	{
#define EMUSE_SCRIPT_FUNCTION_DEFINE( X) void X( ScriptNode * );

#define EMUSE_SCRIPT_FUNCTION_DECLARE( X) void Elypse::Script::X( ScriptNode * caller)

#define VERBOSE_STARTFUNC( func) //EMUSE_LOG_MESSAGE_RELEASE( String( "ScriptFunctionStarted : ") + String( func))

#define RETURN_AS(p_type) caller->get<p_type>() =
		template< typename T, typename U >
		void ReturnAs( ScriptNode * caller, U const & p_value )
		{
			caller->get< T >() = p_value;
		}

#define SCRIPT_ERROR(p_error) ScriptEngine::ScriptError( caller, p_error)

#define GET_AND_EXEC_PARAM(p_type,p_variable,p_index) \
		p_type & p_variable = caller->getAndExecChild<p_type>(p_index);

		namespace
		{
			template< size_t N, typename Tuple, typename ... T > void GetAndExecParamsHelper( ScriptNode * caller, T & ... p_variables );

			template< size_t N, typename Tuple > void GetAndExecParamsHelper( ScriptNode * caller, Tuple & p_tuple )
			{
			}

			template< size_t N, typename Tuple, typename T, typename ... U > void GetAndExecParamsHelper( ScriptNode * caller, Tuple & p_tuple )
			{
				std::get< N >( p_tuple ) = &caller->getAndExecChild< T >( N );
				GetAndExecParamsHelper < N + 1, Tuple, U... > ( caller, p_tuple );
			}
		}

		template< typename T, typename ... U >
		std::tuple< T *, U * ... > GetAndExecParams( ScriptNode * caller )
		{
			std::tuple< T *, U * ... > l_values;
			std::get< 0 >( l_values ) = &caller->getAndExecChild< T >( 0 );
			GetAndExecParamsHelper< 1, std::tuple< T *, U * ... >, U... >( caller, l_values );
			return l_values;
		}

#define GET_AND_EXEC_TWO_PARAM(p_type1,p_variable1,p_type2,p_variable2) \
		p_type1 & p_variable1 = caller->getAndExecChild<p_type1>(0);		\
		p_type2 & p_variable2 = caller->getAndExecChild<p_type2>(1);

#define GET_AND_EXEC_THREE_PARAM(p_type1,p_variable1,p_type2,p_variable2,p_type3,p_variable3) \
		p_type1 & p_variable1 = caller->getAndExecChild<p_type1>(0);		\
		p_type2 & p_variable2 = caller->getAndExecChild<p_type2>(1);		\
		p_type3 & p_variable3 = caller->getAndExecChild<p_type3>(2);

#define GET_AND_EXEC_FOUR_PARAM(p_type1,p_variable1,p_type2,p_variable2,p_type3,p_variable3,p_type4,p_variable4) \
		p_type1 & p_variable1 = caller->getAndExecChild<p_type1>(0);		\
		p_type2 & p_variable2 = caller->getAndExecChild<p_type2>(1);		\
		p_type3 & p_variable3 = caller->getAndExecChild<p_type3>(2);		\
		p_type4 & p_variable4 = caller->getAndExecChild<p_type4>(3);

		//Fonction speciale, for tests.
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Miaou )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_IfBlock )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_WhileLoop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_ForLoop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_ExecuteFunction )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_MultiLineFunction )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Echo )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_ClearScene )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_ClearSceneNode )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_ClearOverlays )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_BindKey )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Return )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_ReturnNull )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Break )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Continue )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Coucou )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_Describe )


		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseLDownScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseRDownScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseMDownScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseLUpScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseMUpScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseRUpScript )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseWheelUpScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetMouseWheelDownScript )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetKeyDownScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetKeyRepeatScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Gen_SetNetworkScript )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_StructGetMember )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Add_Equal_Char_To_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Multiply_Vector3_By_Quat )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Increment_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Increment_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Decrement_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Decrement_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Negate )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_NegateReal )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_NegateInt )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_NegateVe3 )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_Or )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_ModuloInt )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_And )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsEqual )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsDifferent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperior_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperior_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperior_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperior_Real )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperiorOrEqual_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperiorOrEqual_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsSuperiorOrEqual_Real )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferior_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferior_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferior_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferior_Real )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferiorOrEqual_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferiorOrEqual_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_IsInferiorOrEqual_Real )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_SetValue )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_AddValue )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_SubtractValue )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_DivideValue )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ope_MultiplyValue )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_ShowBoundingBox )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetBoundingRadius )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_SetMaterial )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_SetSubMaterial )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_Show )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_Hide )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_SetVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_IsVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_CreateWithSkeleton )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_SetParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetMeshName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetMaterialName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetSubMaterialName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetPhysicsObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_CopyPhysicsObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ent_GetNumSubMaterials )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_CreatePermanent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_CreateContinuous )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_Kill )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_Shift )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_SetBaseTime )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_Exists )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_Play )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_PauseAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_KillAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_PlayAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_GetNumExecs )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_GetTimeLeft )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_GetTimeElapsed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_GetTimeBase )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tmr_GetName )



		EMUSE_SCRIPT_FUNCTION_DEFINE( Tml_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tml_Play )


		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_Set )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_LinearInterpolation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_SquaredInterpolation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_SinusInterpolation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_CubicInterpolation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_BezierInterpolation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_BezierGetLength )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_OperatorArray )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_SnapCoords )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_GetLength )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_ProjectOnScreen )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_DotProduct )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_CrossProduct )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_GetRotationTo )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_Normalise )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ve3_NormalisedCopy )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Qua_FromAxisAngle )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Qua_Slerp )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Qua_GetAngle )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Qua_GetAxis )

		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Exists )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_MousePickup )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Translation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Show )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Hide )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_IsVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Resize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetLRBorderSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetTBBorderSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetLeft )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetTop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetLeft )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetTop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetAbsolutePosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetAbsoluteLeft )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetAbsoluteTop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetHeight )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetWidth )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetCaption )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetCaption )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetMaterial )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetBorderMaterial )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetMouseOverMaterial )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetTextColour )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetTextColour )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_TextureLookUp )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetAction )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetWidth )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetHeight )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetMaterialName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_Clone )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_LimitToParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetFontSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_GetFontSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_ScrollUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_ScaleUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetScaleUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetAlpha )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_RotateUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetRotateUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvE_SetScrollUV )

		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_IsVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_SetVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_Hide )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_HideAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_Show )

		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_SetRotate )
		EMUSE_SCRIPT_FUNCTION_DEFINE( OvL_Rotate )

		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Exists )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Delete )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_RotateAround )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Rotate )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_RotateLocal )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_RotateQuat )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Pitch )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetPitch )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Yaw )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetYaw )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Roll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetRoll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Translate )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_TranslateLocal )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Scale )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetScale )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetXPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetYPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetZPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetDerivedPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Reset )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Group )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Ungroup )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_UngroupAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Recenter )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_AttachTo )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetOrientation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetOrientation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_IsVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Show )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_Hide )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetInheritOrientation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetInheritOrientation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_SetInheritScale )
		EMUSE_SCRIPT_FUNCTION_DEFINE( ScN_GetInheritScale )



		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_SetAutoTrack )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetLocalXAxis )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetLocalYAxis )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetLocalZAxis )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_SetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_AttachTo )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_ModeWireFrame )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_Clamp )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_GetScreenCoords )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cam_IsPositionVisible )

		EMUSE_SCRIPT_FUNCTION_DEFINE( CTx_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( CTx_Refresh )
		EMUSE_SCRIPT_FUNCTION_DEFINE( CTx_SetMain )
		EMUSE_SCRIPT_FUNCTION_DEFINE( CTx_GetCamera )
		EMUSE_SCRIPT_FUNCTION_DEFINE( CTx_SetBackgroundColour )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_SetDirection )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_SetPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_SetDiffuse )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_SetSpecular )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_SetVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_IsVisible )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_Show )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Lgh_Hide )


		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Real_To_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Real_To_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Int_To_Real )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Int_To_Bool )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Int_To_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Int_To_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_String_To_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_String_To_Real )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_String_To_Bool )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_String_To_Char )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Bool_To_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Bool_To_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Char_To_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Char_To_Int )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Vector3_To_String )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Cst_Quaternion_To_String )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_Add )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_AddDefault )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_RemoveIndex )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_GetSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_Clear )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_Set )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_Get )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Arr_IsEmpty )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Add )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_AddDef )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Size )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Has )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Set )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Find )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Clear )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Empty )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_Erase )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_IterBegin )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_IterFind )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_IterEnd )


		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Add )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_AddDef )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Size )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Has )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Set )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Find )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Clear )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Empty )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_Erase )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_IterBegin )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_IterFind )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_IterEnd )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Add )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_AddDef )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Size )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Has )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Set )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Find )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Clear )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Empty )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_Erase )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_IterBegin )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_IterFind )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_IterEnd )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Int_EraseIter )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_String_EraseIter )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Map_Real_EraseIter )


		EMUSE_SCRIPT_FUNCTION_DEFINE( Sit_Next )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Sit_Prev )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Sit_Key )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Sit_Data )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Iit_Next )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Iit_Prev )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Iit_Key )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Iit_Data )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Rit_Next )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Rit_Prev )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Rit_Key )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Rit_Data )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Par_First )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Par_Second )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Par_Set )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_Set3 )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_Set4 )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_GetR )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_GetG )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_GetB )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_GetA )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_SetR )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_SetG )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_SetB )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Col_SetA )


		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Play )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Play_Global )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Play_All )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Pause_Global )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Pause_All )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Stop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Stop_Global )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_Stop_All )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_SetVolume )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_SetSFXVolume )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_SetMusicVolume )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_MuteSFX )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Snd_MuteMusic )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Pll_Start )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pll_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pll_Stop )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Por_GetTargetName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Por_GetTargetZone )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_CreateInstance )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_DestroyInstance )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Play )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Stop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_SetVolume )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_SetLooped )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Mute )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_ChangeVideo )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Initialise )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_Reset )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_DelayObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_DelayOverlay )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_InitialiseObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_InitialiseOverlay )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Vid_SetVolumePercent )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Mus_StartDownload )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mus_DownloadSeparable )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mus_GetDirectory )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_ObjectDuplicate )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_ObjectDelete )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_ImportMesh )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_GetGroundCoords )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_SaveScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_MousePickupObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_ThreadedStringFromUrl )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_SetSessionCookie )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_GetWebFileType )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_StringFromUrl )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_OpenUrl )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_ExecuteJavaScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_Quit )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_ClosestObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_TestAllEntities )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_GetCharWidth )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_GetLineWidth )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_GetCurrentDirectory )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_GetMD5Hash )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Spc_SetCursor )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Rand )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Abs )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Floor )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Ceil )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Round )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Min )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Max )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Minmax )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Sin )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Cos )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Tan )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_ASin )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_ACos )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_ATan )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Sqr )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mth_Sqrt )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Tim_GetCurrentSecond )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tim_GetCurrentMinute )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Tim_GetCurrentHour )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Mir_SetAlpha )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mir_Update )

		EMUSE_SCRIPT_FUNCTION_DEFINE( PEf_Enable )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Wim_Reload )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Wim_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Wim_Delete )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Pub_Reload )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Sce_Load )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Sce_Unload )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Sce_Shadows )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Substr )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Strlen )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Contains )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Split )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_SplitOne )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Trim )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Find )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_GetChar )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_SetChar )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Empty )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Clear )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Replace )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Erase )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Lower )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Str_Upper )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Chr_IsLower )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Chr_IsUpper )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Chr_IsAlpha )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Chr_IsNumeral )

		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_Exists )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_DestroyAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_GetObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_AddObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_RemObject )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_ChainAll )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_StartAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_PauseAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_StopAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetTimeAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetAnimationTimeScale )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetAnimationWeight )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetAnimationTimeIn )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_StopAllAnimations )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_PauseAllAnimations )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_ChainAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetAnimationTimeOut )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetAnimationReversed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_SetAnimationLooped )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AoG_RestartAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AOb_GetAnimation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AOb_GetNumPlayingAnimations )
		EMUSE_SCRIPT_FUNCTION_DEFINE( AOb_GetPlayingAnimationName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_Start )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_Stop )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_SetTime )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_GetLength )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_SetNext )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_SetLooped )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_SetReversed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Ani_Restart )

		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetSpeed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_SetSpeed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetAngularSpeed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_SetAngularSpeed )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_AddForce )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_SetForce )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_AddTorque )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_SetTorque )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_SetIgnoreGravity )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetIgnoreGravity )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_SetEnabled )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_IsEnabled )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_CollisionCheck )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_CheckAllCollisions )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_ReassertPosition )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetNumCollisions )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_GetNumCollisionsWith )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_Reset )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_AddBoundingBox )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_AddBoundingSphere )
		EMUSE_SCRIPT_FUNCTION_DEFINE( POb_AddBoundingMesh )


		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetCurrentSimulation )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetGravity )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_GetGravity )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetTimescale )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_GetTimescale )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetSteptime )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_GetSteptime )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_GetSteptimeLimit )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetErp )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetCfm )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetAutoUpdate )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_Update )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_SetUpdateScript )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_Raytrace )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhS_ClearObjects )

		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_SetFriction )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_GetFriction )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_GetAddFriction )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_SetBouncyness )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_GetBouncyness )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_SetSoftConstraints )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_GetSoftCfm )
		EMUSE_SCRIPT_FUNCTION_DEFINE( PhM_GetSoftErp )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Uni_GetCameraByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Uni_GetEntityByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Uni_GetLightByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Uni_GetSceneNodeByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Uni_GetUniverseList )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Uni_GetSceneList )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_PackInt )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_PackReal )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_PackVector3 )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_PackQuaternion )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_UnpackInt )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_UnpackReal )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_UnpackVector3 )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Pck_UnpackQuaternion )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Seq_Start )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Seq_Pause )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Seq_Stop )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Nwk_CreateClient )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Nwk_ConnectClient )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Nwk_CloseClient )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Nwk_ClientSendMessage )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_GetByName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_Exists )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_CreateCopy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_ScrollUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_SetScrollUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_RotateUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_SetRotateUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_ScaleUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_SetScaleUV )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_CreateTextureUnit )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_ChangeImage )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_GetImageName )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Mat_CreateMatCopy )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_OpenForRead )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_CloseForRead )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_Destroy )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_WriteLine )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_WriteBuffer )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_ReadLine )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Con_ReadBuffer )

		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_Create )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_Exists )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_SetMaterial )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_SetParent )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_SetDefaultSize )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_Clear )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_AddElement )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_AddSizedElementAt )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_RemoveIndex )
		EMUSE_SCRIPT_FUNCTION_DEFINE( Bil_Destroy )

	}
}

#endif
