/*
See LICENSE file in root folder
*/
#ifndef ___VERSION_H___
#define ___VERSION_H___

#define ELYPSE_VERSION_MAIN			0
#define ELYPSE_VERSION_SUB			9
#define ELYPSE_VERSION_REVISION		4
#define ELYPSE_VERSION_PATCH		0
#define ELYPSE_VERSION ((ELYPSE_VERSION_MAIN * 1000000) + (ELYPSE_VERSION_SUB * 10000) + (ELYPSE_VERSION_REVISION * 100) + (ELYPSE_VERSION_PATCH))

#define CHECK_ELYPSE_VERSION( X) ((X) <= (ELYPSE_VERSION))

#endif
