name: Build

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        # os: [[ubuntu-latest,x64-linux], [windows-latest,x64-windows], [macos-latest,x64-osx]]
        os: [[windows-latest,x64-windows]]
        buildType: [Release]

    runs-on: ${{ matrix.os[0] }}

    steps:
    - uses: actions/checkout@v2

    - name: Install necessary packages (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: sudo apt-get install libxi-dev libgl1-mesa-dev libglu1-mesa-dev mesa-common-dev libxrandr-dev libxxf86vm-dev libxaw7-dev yasm

    # Restore from cache the previously built ports. If cache-miss, download, build vcpkg.
    - name: Setup vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v4
      with:
        vcpkgGitCommitId: '7e3d3beac5ca6fe8aab4599d4e1d8ce270ccdea8'
        setupOnly: true

    - name: Install dependencies from vcpkg
      shell: bash
      run: $VCPKG_ROOT/vcpkg install boost-date-time:${{ matrix.os[1] }} boost-system:${{ matrix.os[1] }} boost-filesystem:${{ matrix.os[1] }} curl:${{ matrix.os[1] }} ogre:${{ matrix.os[1] }} ode:${{ matrix.os[1] }} zlib:${{ matrix.os[1] }} libzip:${{ matrix.os[1] }} freetype:${{ matrix.os[1] }} libsndfile:${{ matrix.os[1] }} mpg123:${{ matrix.os[1] }} openal-soft:${{ matrix.os[1] }} opencv:${{ matrix.os[1] }} wxwidgets:${{ matrix.os[1] }}

    - name: Checkout submodules
      run: |
        git submodule update --init -- "CMake"
        git submodule update --init -- "data"

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build-${{ matrix.buildType }}

    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      shell: bash
      working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/package/elypse -DPROJECTS_USE_PRECOMPILED_HEADERS=ON -DBUILD_PLUGINS_ELYPSE_FFX=OFF -DBUILD_PLUGINS_ELYPSE_OCX=OFF -DBUILD_MINILINE_SERVER=OFF

    - name: Configure CMake (Non Windows)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/package/elypse -DPROJECTS_USE_PRECOMPILED_HEADERS=OFF -DBUILD_PLUGINS_ELYPSE_FFX=OFF -DBUILD_PLUGINS_ELYPSE_OCX=OFF -DBUILD_MINILINE_SERVER=OFF

    - name: Build
      working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
      shell: bash
      run: cmake --build . --parallel 2 --config ${{ matrix.buildType }}

    - name: Prepare package
      if: github.event_name == 'push'
      working-directory: ${{runner.workspace}}/build-${{ matrix.buildType }}
      shell: bash
      run: |
        cmake --install . --config ${{ matrix.buildType }}
        7z a $GITHUB_WORKSPACE/Elypse-${{ matrix.os[1] }}.zip $GITHUB_WORKSPACE/package/elypse/

    - name: Upload package
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v2
      with:
        name: Elypse-${{ matrix.os[1] }}.zip
        path: ${{ github.workspace }}/Elypse-${{ matrix.os[1] }}.zip
